{
 "title": "WN-app Dashboard",
 "tags": [
  "example",
  "health"
 ],
 "panels": [
  {
   "title": "Состояние приложения",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "h": 8, "w": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"web_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время отклика",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "h": 8, "w": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_response_time" }
   ]
  },
  {
   "title": "Количество Запросов",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "request_count{job=\"web_app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}